export const PARENTHESIS_OPEN = '(';
export const PARENTHESIS_CLOSE = ')';
export const BRACKET_OPEN = '[';
export const BRACKET_CLOSE = ']';
export const CURLY_OPEN = '{';
export const CURLY_CLOSE = '}';
export const DOUBLEQUOTE = '"';
export const SPACE = ' ';
export const NEWLINE = /\r?\n/g;
export const COMMA = ',';
export const LETTER = /[a-zA-Z]/;
export const NUMBER = /[0-9]/;
export const Equal = '=';